# Generated by Django 3.2.5 on 2021-07-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=350)),
                ('subject', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
