# Generated by Django 3.2.5 on 2021-07-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clg', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='enroll',
            new_name='rollno',
        ),
    ]
