# Generated by Django 3.2.5 on 2021-07-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg', '0005_rename_enroll_payment_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
